apiVersion: v1
kind: Service
metadata:
  name: service-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-nginx
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80