name: Replicate Buld Nodejs and deploy on aws

on:
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: [self-hosted]
    container:
      image: ubuntu:jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install deps
        run: npm ci

      - name: Build zip
        run: npm run build-output-zip

      - name: Deploy (actually test if AWS CLI is installed)
        run: aws --version
