name: Replicate Build Nodejs and deploy on aws

on:
  workflow_dispatch:

defaults:
  run:
    working-directory: ./foo

jobs:
  build-test-deploy:
    runs-on: [self-hosted]
    container:
      image: ubuntu:jammy
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install AWS CLI v2
        run: |
          apt-get update
          apt-get install -y unzip curl
          cd "$(mktemp -d)"
          curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -q awscliv2.zip
          ./aws/install --update

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install deps
        run: npm ci

      - name: Build zip
        run: npm run build-output-zip

      - name: Deploy (actually test if AWS CLI is installed)
        run: aws --version
